version: "3.3"

services:
  mysql:
    image: mysql:8.0.26
    container_name: protector_mysql
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./mysqldb/:/var/lib/mysql

  grafana:
    image: grafana/grafana:8.2.1
    container_name: protector_grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
