version: "3.3"

services:
  mongo:
    image: mongo:4.4.7
    container_name: protector_mongo
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data/:/data/db

  grafana:
    image: grafana/grafana:8.2.1
    container_name: protector_grafana
    ports:
      - 3000:3000
